### ISSUE TITLE
Issue getting the Module to import

### ISSUE THREAD

**Issue by pauloensign** [polygon-io/client-js#100]
When using the import {restClient} from "@polygon.io/client-js"; I am getting an error that 

![image](https://user-images.githubusercontent.com/52921656/186752861-bb2d23e2-3457-447d-8fc8-b299a45c2ada.png)

I can see in the source tab of the inspect that it is grabbing the main.js file as shown here which should be the correct file to get the rest or websocket libraries

![image](https://user-images.githubusercontent.com/52921656/186753126-71d65b16-7882-4db8-a220-f72b9a265516.png)

the file is formatted as a commonjs file and not an ES Module. What am I missing to get the api module to work?
thanks

**Comment by yehudabortz** [comment]
@pauloensign Sorry for the delayed response. Have you resolved this?
