### ISSUE TITLE
Incorrect interface for ISession

### ISSUE THREAD

**Issue by jdconley** [polygon-io/client-js#120]
Using v6.1.3.

I was attempting to read summary data on the Launchpad API. I noticed the session interface has a typo.

```
export interface ISession {
    ...
    pervious_close: number;
    ...
}
```

Based on the data I see that should be `previous_close:  number;`

**Comment by mpatel18** [comment]
Hello @jdconley,
Thank you for reporting this issue! The latest release of 6.2.0 should correct this problem.
