### ISSUE TITLE
https://api.polygon.io/v2/aggs/ticker/X:BTCUSD/range/1/day/2023-01-09/2023-01-09?adjusted=true&sort=asc&limit=120

### ISSUE THREAD

**Issue by CharliesAngel1** [polygon-io/client-js#124]

**Comment by teambailey** [comment]
Hey @CharliesAngel1, would it be safe to assume that you've opened this issue erroneously?

I've editing the title to remove the api key from the url query but it will still be searchable and there's nothing that can be done about that. We advise that you generate a new key via the [dashboard](https://polygon.io/dashboard/api-keys) and delete the one posted here. If you require some assistance with this query please reach out to our support team and they would be happy to help. See our [Contact Us](https://polygon.io/contact) page for several ways of getting in touch!
