### ISSUE TITLE
Some missing props in ticker details

### ISSUE THREAD

**Issue by hsynlms** [polygon-io/client-js#128]
I figured out that there are some missing props in the ticker details response.

1. `ticker_root`
2. `address.postal_code`
3. `round_lot`

**Ref:** https://github.com/polygon-io/client-js/blob/master/src/rest/reference/tickerDetails.ts

**Comment by timetraveler328** [comment]
@hsynlms appreciate the PR, we'll get a patch release out tomorrow with the changes

**Comment by timetraveler328** [comment]
This change has been published in v7.0.1
