### ISSUE TITLE
Forex aggregatesGroupedDaily endpoint url seems incorrect

### ISSUE THREAD

**Issue by ttogola** [polygon-io/client-js#134]
The url [here](https://github.com/polygon-io/client-js/blob/655e3214be972ba4a35cf53eb9c1b4aca73206cb/src/rest/forex/aggregatesGroupedDaily.ts#L16) doesn't match the current documentation. Instead of `forex` it should contain `fx` as documented [here](https://polygon.io/docs/forex/get_v2_aggs_grouped_locale_global_market_fx__date).

I noticed this because calling the documented `fx` url works, but using the polygon js client returns an empty list for the same endpoint. It seems likely that the issue is caused by this mismatched url.

**Comment by timetraveler328** [comment]
@ttogola I've released a fix for this in v7.0.3. Thanks for filing
