### ISSUE TITLE
v1.1.0 release not available on NPM

### ISSUE THREAD

**Issue by benbarber** [polygon-io/client-js#14]
Could you publish the v1.1.0 release to NPM please, or is there another reason its not available on there yet?

**Comment by bassochette** [comment]
It has been rolled back.
It has a breaking change on the sockets api.

**Comment by benbarber** [comment]
That makes sense, it should be 2.0 if it includes a breaking change.

Any idea when this is likely to be done?

Thanks

**Comment by robax** [comment]
any updates on V2?

**Comment by jtbales** [comment]
Same, I really like the types added in that release. I'm using it directly with ` "polygon.io": "git+https://github.com/polygon-io/client-js.git",` 

or just `npm i git+https://github.com/polygon-io/client-js.git`

**Comment by jtbales** [comment]
at least make a release with the add typescript types. they are very helpful

**Comment by bassochette** [comment]
Sorry for the delay, I was not supposed to be a maintainer anymore.

SO I published the current typing as V2.0.1 in npm.

If someone from polygon could contact me to take ownership of the npm package please do!

**Comment by Sieabah** [comment]
I don't believe this ended up working. The package.json points to the lib folder which does not exist in v2.0.0.

**Comment by bassochette** [comment]
@Sieabah my bad, I publish v2.0.1 without the built sources. 

v2.0.2 should should fix your issue.

- repl example in js: https://repl.it/@JulienPrugne/polygonio-v2-js
- repl example in ts: https://repl.it/@JulienPrugne/polygonio-v2
