### ISSUE TITLE
Incorrect stock financials field names

### ISSUE THREAD

**Issue by hsynlms** [polygon-io/client-js#141]
In the package below fields are named incorrectly according to [the related API doc page](https://polygon.io/docs/stocks/launchpad/get_vx_reference_financials).

- `source_filling_url` should have been `source_filing_url`
https://github.com/polygon-io/client-js/blob/master/src/rest/reference/stockFinancials.ts#L30
- `filling_date` should have been `filing_date`
https://github.com/polygon-io/client-js/blob/master/src/rest/reference/stockFinancials.ts#L55
https://github.com/polygon-io/client-js/blob/master/src/rest/reference/stockFinancials.ts#L69

**Comment by timetraveler328** [comment]
@hsynlms thanks for the PR! This is merged and released in v7.1.1.
