### ISSUE TITLE
Websocket does not work as in tutorial!

### ISSUE THREAD

**Issue by illogikal** [polygon-io/client-js#16]
ENV: Ubuntu 18, node v13.8.0

I copied the readme code for the websocket and when I run it I get:

Uncaught:
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object

It seems the websocket client you are using does not handle sending Objects directly, how is this fixed?

**Comment by teambailey** [comment]
Corrected. Thanks for bring that to our attention!
