### ISSUE TITLE
stocks.snapshotSingleTicker does not seem to work on the weekend

### ISSUE THREAD

**Issue by illogikal** [polygon-io/client-js#17]
And if you request using the client, it gives a 404 which is not handled by the client which then throws an error.

**Comment by Stormy110** [comment]
Hello, thank you for reaching out! The snapshot ticker only responses with data if the market is open. Thus requesting those endpoints on the weekend would give no response.

**Comment by Stormy110** [comment]
Snapshot only works during market hours.
