### ISSUE TITLE
cannot run examples

### ISSUE THREAD

**Issue by cokeito** [polygon-io/client-js#172]
Hello, i've try to run the examples according to the documentation, but after i try to run any example i got this error

coke@moo ~/client-js-7.2.5/examples/rest $ node options-last_trade.js
node:internal/modules/cjs/loader:560
throw e;
^

Error: Cannot find module '/home/coke/client-js-7.2.5/dist/main.cjs'
at createEsmNotFoundErr (node:internal/modules/cjs/loader:1112:15)
at finalizeEsmResolution (node:internal/modules/cjs/loader:1105:15)
at trySelf (node:internal/modules/cjs/loader:554:12)
at Module._resolveFilename (node:internal/modules/cjs/loader:1067:24)
at Module._load (node:internal/modules/cjs/loader:934:27)
at Module.require (node:internal/modules/cjs/loader:1157:19)
at require (node:internal/modules/helpers:119:18)
at Object.<anonymous> (/home/coke/client-js-7.2.5/examples/rest/options-last_trade.js:1:24)
at Module._compile (node:internal/modules/cjs/loader:1275:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1329:10) {
code: 'MODULE_NOT_FOUND',
path: '/home/coke/client-js-7.2.5/package.json'
}

Node.js v19.8.1

im running under debian 11 with

coke@moo ~/client-js-7.2.5/examples/rest $ node -v
v19.8.1

coke@moo ~/client-js-7.2.5/examples/rest $ npm -v
9.5.1

thx in advance!

**Comment by cokeito** [comment]
Sure, here it is :)

coke@moo ~/_prj/polygon.io/client-js (master) $ npm list
@polygon.io/client-js@7.2.5 /home/coke/_prj/polygon.io/client-js
├── @polygon.io/client-js@7.2.5
├── @types/chai@4.2.22
├── @types/mocha@9.0.0
├── @types/node@16.11.11
├── @types/sinon@10.0.6
├── @types/websocket@1.0.4
├── chai@4.3.4
├── cross-fetch@3.1.5
├── husky@7.0.4
├── lint-staged@12.1.2
├── mocha@9.2.2
├── prettier@2.5.1
├── query-string@7.0.1
├── sinon@12.0.1
├── ts-node@10.9.1
├── tsup@6.7.0
├── typedoc@0.22.11
├── typescript@4.5.2
└── websocket@1.0.34

coke@amnesia ~/_prj/polygon.io/client-js (master) $

**Comment by cokeito** [comment]
Sure, here it is!

coke@moo ~/_prj/polygon.io/client-js (master) $ npm list
@polygon.io/client-js@7.2.5 /home/coke/_prj/polygon.io/client-js
├── @polygon.io/client-js@7.2.5
├── @types/chai@4.2.22
├── @types/mocha@9.0.0
├── @types/node@16.11.11
├── @types/sinon@10.0.6
├── @types/websocket@1.0.4
├── chai@4.3.4
├── cross-fetch@3.1.5
├── husky@7.0.4
├── lint-staged@12.1.2
├── mocha@9.2.2
├── prettier@2.5.1
├── query-string@7.0.1
├── sinon@12.0.1
├── ts-node@10.9.1
├── tsup@6.7.0
├── typedoc@0.22.11
├── typescript@4.5.2
└── websocket@1.0.34

**Comment by timetraveler328** [comment]
@cokeito I've updated the examples to make it easier to run them out of the box, and to use esmodule syntax, which I think is why you were having issues. If you pull down the latest version, you should be able to do `POLY_API_KEY=yourAPIKey node examples/rest/crypto-aggregates_bars.js`. Let me know if that does the trick

**Comment by justinpolygon** [comment]
Hey @cokeito, I'm going to close this since the latest release fixed the issue. Thanks for reporting it.

Please try and run:
`POLY_API_KEY=yourAPIKey node examples/rest/crypto-aggregates_bars.js`

If you're still seeing this please comment and we'll assist.
