### ISSUE TITLE
formatIQuoteV2Raw - wrong field for askPrice 

### ISSUE THREAD

**Issue by 3ffon** [polygon-io/client-js#18]
Hi

according to website docs,
ask price would be P for quote object (IQuoteV2Raw)
and on formatIQuoteV2Raw  function, you use raw.p for askPrice

file: v2HistoricQuotes.ts
Line 69: `askPrice: raw.p,` - should be raw.P

**Comment by tharnach** [comment]
This is resolved in [v2.1.3](https://github.com/polygon-io/client-js/releases/tag/v2.1.3)
