### ISSUE TITLE
Client constructor, wrong parameter type?

### ISSUE THREAD

**Issue by emilje** [polygon-io/client-js#181]
I am trying to enable pagination, and I should set the options (3rd param of restClient) to
```
{
   pagination: true
}
```

```
error TS2345: Argument of type '{ pagination: boolean; }' is not assignable to parameter of type 'IRequestInit'.
  Object literal may only specify known properties, and 'pagination' does not exist in type 'IRequestInit'.

5     pagination: true
```
However, it seems that the `restClient`'s third param is of type `IRequestOptions` which does not contain this key. 
`IGlobalOptions` however does include it. 

Am I doing something wrong, or is the `restClient`'s third param possibly of wrong type?

**Comment by justinpolygon** [comment]
Hey @emilje, we added this in `v7.3` so it could be that you're not running the latest version? If you're running the latest `v7.3.1` then the following example should just work.

```javascript
import('@polygon.io/client-js').then(({ restClient }) => {
	const globalFetchOptions = {
		pagination: true,
	};
	const rest = restClient("XXXX", "https://api.polygon.io", globalFetchOptions);
	rest.stocks.aggregates("TSLA", 1, "minute", "2022-01-01", "2023-08-31", { limit: 50000 }).then((data) => {
	    const resultCount = data.length;
	    console.log("Result count:", resultCount);
	}).catch(e => {
		console.error('An error happened:', e);
	});
});
```

Can you test that out and see if it solves your problem? We should probably update the docs and mention that `v7.3.1` is required for pagination.

**Comment by emilje** [comment]
> ```js
> import('@polygon.io/client-js').then(({ restClient }) => {
> 	const globalFetchOptions = {
> 		pagination: true,
> 	};
> 	const rest = restClient("XXXX", "https://api.polygon.io", globalFetchOptions);
> 	rest.stocks.aggregates("TSLA", 1, "minute", "2022-01-01", "2023-08-31", { limit: 50000 }).then((data) => {
> 	    const resultCount = data.length;
> 	    console.log("Result count:", resultCount);
> 	}).catch(e => {
> 		console.error('An error happened:', e);
> 	});
> });
> ```

Hi, yes I have 7.3.1, and the issue is exactly what I wrote. Could you try writing your code in a .ts file and see if you can run it? pagination does not exist on `IRequestOptions `

**Comment by justinpolygon** [comment]
Here's what I'm seeing. I did have to change how the results were printed in that the example was wrong. I was doing `const resultCount = data.length;` but just changed it to print data. I'll update the example.

```
jw@31de8eb2da18:~/x# cat x.ts
import('@polygon.io/client-js').then(({ restClient }) => {
	const globalFetchOptions = {
		pagination: true,
		trace: true,
	};
	const rest = restClient("XXXXX", "https://api.polygon.io", globalFetchOptions);
	rest.stocks.aggregates("TSLA", 1, "minute", "2022-01-01", "2023-08-31", { limit: 50000 }).then((data) => {
	    console.log("Result count:", data);
	}).catch(e => {
		console.error('An error happened:', e);
	});
});
```

Then running it:

```
jw@31de8eb2da18:~/x# jw x.ts
Request URL:  https://api.polygon.io/v2/aggs/ticker/TSLA/range/1/minute/2022-01-01/2023-08-31?limit=50000
Request Headers:  { Authorization: 'Bearer REDACTED' }
Response Headers:  Headers {
  [Symbol(map)]: [Object: null prototype] {
    server: [ 'nginx/1.19.2' ],
    date: [ 'Thu, 05 Oct 2023 17:56:47 GMT' ],
    'content-type': [ 'application/json' ],
    'transfer-encoding': [ 'chunked' ],
    connection: [ 'keep-alive' ],
    'content-encoding': [ 'gzip' ],
    vary: [ 'Accept-Encoding' ],
    'x-request-id': [ '3e586d127185fed3db3f13d0aaa3d7db' ],
    'strict-transport-security': [ 'max-age=15724800; includeSubDomains' ]
  }
}
...
Result count: {
  ticker: 'TSLA',
  queryCount: 7102,
  resultsCount: 7102,
  adjusted: true,
  results: [
    {
      v: 58551,
      vw: 371.511,
      o: 369.9133,
      c: 373.83,
      h: 373.83,
      l: 368.6667,
      t: 1641200400000,
      n: 1343
    },
    ... 357002 more items
  ],
  status: 'OK',
  request_id: '9c8e05f1911d3520d23feb772e09c3e9',
  count: 357102,
  next_url: null
}
```

Here's my node version:

```
jw@31de8eb2da18:~/x# node --version
v19.8.1
```

**Comment by justinpolygon** [comment]
Ah yeah, sorry I checked with a colleague and looks like since this is typescript, seems like that type probably doesn't have the attribute added. I'll check this out and reply shortly.

**Comment by emilje** [comment]
> this out and reply shortly

great, let me know!

**Comment by justinpolygon** [comment]
Hi @emilje, we're rolled out `7.3.2` with a fix. Mind testing it out when you have a minute? Thanks.

**Comment by emilje** [comment]
> Hi @emilje, we're rolled out `7.3.2` with a fix. Mind testing it out when you have a minute? Thanks.

works as expected, cheers!
