### ISSUE TITLE
Importing in node

### ISSUE THREAD

**Issue by dschlesinger** [polygon-io/client-js#186]
importing as described in the documentation fails because of @.

npm install --save @polygon.io/client-js

Error:
At line:1 char:20

> + npm install --save @polygon.io/client-js
> The splatting operator '@' cannot be used to reference variables in an expression. '@polygon' can be used only as an argument to a command. To reference variables in an expression use '$polygon'.        
>     + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
>     + FullyQualifiedErrorId : SplattingNotPermitted

The solution is to put quotes around the package like this 

npm install --save '@polygon.io/client-js'

It would be helpful if you added this to your documentation.

**Comment by justinpolygon** [comment]
Great suggestion. Will do. Thanks.
