### ISSUE TITLE
Symbol field is not case insensitive

### ISSUE THREAD

**Issue by illogikal** [polygon-io/client-js#19]
In the api explorer, the symbol field does not work unless all letters are capitalized. Options to fix:

Change the backend to uppercase the letters.
Change the clients to uppercase the letters. 
Provide an error that mentions the letters being lowercased as an issue.

**Comment by teambailey** [comment]
So a symbol can have mixed casing depending on the exchange it's listed on and the SIP that is reporting it. These SIPs have different formats they follow for symbology. One major difference is when it comes to the suffixes. Here's a link to the [NYSE documentation](https://www.nyse.com/publicdocs/nyse/data/NYSE_Symbology_Spec_v1.0c.pdf) on this matter. Also see this [blog post](https://polygon.io/blog/understanding-the-sips/) we created to help explain the SIPs for further information.
