### ISSUE TITLE
Aggregates API throws error when there are no results

### ISSUE THREAD

**Issue by mattnguyen1** [polygon-io/client-js#23]
When making a call to the aggregates API that would result in a `resultCount` of 0, the API does not return a `results` field which causes this [line](https://github.com/polygon-io/client-js/blob/master/src/rest/stocks/aggregates.ts#L63) to throw an error whenever you make such a request via `client.stocks.aggregates()`. 

There should be a check here that the results object exists, and the type for `IAggResponseRaw` should have `results` be optional.

**Comment by teambailey** [comment]
Thank you for your interest in Polygon.io! The [v4.0.2](https://github.com/polygon-io/client-js/releases/tag/v4.0.2) release should have addressed this issue.
