### ISSUE TITLE
Consumer facing type definitions?

### ISSUE THREAD

**Issue by adam-arthur** [polygon-io/client-js#25]
Hey!

I noticed the whole source code is pretty much typed correctly via typescript, but the built library does not export these typings. 

Is there a reason for this? It should be fairly trivial to expose them... would make UX of using the library much better.

I can submit a PR if no concerns

**Comment by bassochette** [comment]
This issue duplicate #14 
The types where already in the repo.
They are now tagged under v2 and published on NPM.

Not in the repo yet but in a PR
