### ISSUE TITLE
How is the reconnect handled?

### ISSUE THREAD

**Issue by jimin4** [polygon-io/client-js#32]
According to the source code, it looks like reconnect mechanism isn't there. Is this the case? I think there should be a reconnect functionality for this client to be really useful.

**Comment by sinazPSI** [comment]
You can see a basic reconnection logic implemented in the example directory. The logic is that on disconnect, it will call the connect method again after waiting 2 seconds:

https://github.com/polygon-io/client-js/blob/4d79482afbbe5a673f0e508fb9336021dedbdf7d/websocket_example/advanced.js#L51-L53
