### ISSUE TITLE
Version 2.1.2 is not backward compatible with v2.0.2

### ISSUE THREAD

**Issue by hardillb** [polygon-io/client-js#37]
[Semantic versioning](https://docs.npmjs.com/about-semantic-versioning) says that a change to the minor release number should be fully backward compatible with the previous version. But code written for v2.0.x will not run with v2.1.x

e.g.

```
const {websocketClient} = require('polygon.io')

const ws = websocketClient(node.apiKey).stocks()

ws.on('open', () => {
  send(`{"action":"subscribe","params":"IBM"}`)
})
```

This works fine at v2.0.2 but fails at v2.1.2 complaining that `ws` is not a event handler
```
TypeError: ws.on is not a function
```

**Comment by teambailey** [comment]
Thank you for the feedback and interest in our service! We always try to follow best practices but looks like we let this one slip through the cracks. Thanks again for bring it to our attention 👍
