### ISSUE TITLE
v2HistoricTrades Fails

### ISSUE THREAD

**Issue by hardillb** [polygon-io/client-js#38]
https://github.com/polygon-io/client-js/blob/master/src/rest/stocks/v2HistoricTrades.ts#L80

As described in the [docs](https://polygon.io/docs/get_v2_ticks_stocks_trades__ticker___date__anchor)

```
export const formatIV2HistoricTradeResultRaw = (
  raw: IV2HistoricTradesResultRaw
): IV2HistoricTradesResultFormatted => ({
  ...raw,
  ticks: raw.ticks.map(formatITradeV2Raw)
});
```

Should be

```
export const formatIV2HistoricTradeResultRaw = (
  raw: IV2HistoricTradesResultRaw
): IV2HistoricTradesResultFormatted => ({
  ...raw,
  ticks: raw.results.map(formatITradeV2Raw)
});
```

**Comment by tharnach** [comment]
This is resolved in [v2.1.3](https://github.com/polygon-io/client-js/releases/tag/v2.1.3)
