### ISSUE TITLE
Ticker API - Response Data

### ISSUE THREAD

**Issue by YogiBear52** [polygon-io/client-js#42]
Ticker API response, as in the library is form like: (Array of ITickers)
![image](https://user-images.githubusercontent.com/10381032/119790247-729e6d80-bedc-11eb-867e-a6bba2286928.png)

But the actual result is form like: (Object with other fields, the results field is the array of ITickers)
![image](https://user-images.githubusercontent.com/10381032/119790315-81852000-bedc-11eb-914b-05582409b41a.png)

It makes use write workarounds.

**Comment by 0xmax** [comment]
Any update on this? Is the JS client still maintained?

**Comment by teambailey** [comment]
Hi @YogiBear52 - Thank you for your interest in Polygon.io! The latest release, [v4.0.2](https://github.com/polygon-io/client-js/releases/tag/v4.0.2), should correct this issue.
