### ISSUE TITLE
Expanded Documentation

### ISSUE THREAD

**Issue by danpastori** [polygon-io/client-js#43]
Hi All,

I'm really loving Polygon and am super stoked to implement it into some apps. The documentation on using the API is top notch and beautifully done. However, I notice some of the client libraries, there are minimal code examples and takes a little bit to correlate how to use the library with the documentation available.

With that being said, I'd love to work on writing some docs to help you out. I'll be heavily implementing the PHP and JS libraries and can work on documenting them and providing code examples if this is something you are interested in.

## Approach
I'd write everything in markdown so you can use it in the Github Wiki, or throw it into the documentation engine of your choice.

Would this be helpful?

**Comment by teambailey** [comment]
Hi @danpastori - A newly refactored version is available, [v4.0.2](https://github.com/polygon-io/client-js/releases/tag/v4.0.2). Thank you for your interest in our service!
