### ISSUE TITLE
Reference Tickers V3

### ISSUE THREAD

**Issue by LoganVS** [polygon-io/client-js#45]
Hi,

When will v3/reference/tickers be supported in the client library?

Thanks.

**Comment by jdgriffith** [comment]
I created a PR for this very thing but no response from anyone. It's been crickets. https://github.com/polygon-io/client-js/pull/46

**Comment by LoganVS** [comment]
Yeah, unfortunately I'm going to have to assume this project is dead and find a new market data provider.  ☹️

**Comment by jdgriffith** [comment]
The data provider is good - the API client support is not it seems.

**Comment by LoganVS** [comment]
Fair. I'd prefer to use a product that offers both though!

**Comment by tharnach** [comment]
This issue has been resolved in [v2.1.3](https://github.com/polygon-io/client-js/releases/tag/v2.1.3)
