### ISSUE TITLE
Out of date ILastQuoteResult and ILastTradeResult

### ISSUE THREAD

**Issue by adrianlee** [polygon-io/client-js#55]
#48 Introduced some breaking changes. The REST endpoints were updated to point to v2 for LastQuote and LastTrade but the `ILastQuoteResult` and `ILastTradeResult` return types were not updated in parallel.

**Comment by teambailey** [comment]
Thank you for your interest in Polygon.io! The [v4.0.2](https://github.com/polygon-io/client-js/releases/tag/v4.0.2) release should have addressed this issue.
