### ISSUE TITLE
Bug/typo in return type of results in lastQuote.ts

### ISSUE THREAD

**Issue by Akash9L** [polygon-io/client-js#73]
### File : client-js/src/rest/stocks/lastQuote.ts
**The return type of property "results" of the Interface "ILastQuote" should not be an array according to the documentation.** 

```
export interface ILastQuote {
  request_id?: string;
  status?: string;
  results?: ITradeInfo[]; // => results?: ITradeInfo ;
}
```

**Comment by tharnach** [comment]
Resolved by https://github.com/polygon-io/client-js/pull/74
