### ISSUE TITLE
Typo in IMarketHoliday Interface

### ISSUE THREAD

**Issue by fazamutash** [polygon-io/client-js#87]
Hi, there is a typo on https://github.com/polygon-io/client-js/blob/master/src/rest/reference/marketHolidays.ts#L10 where it should be `status` instead of `staus`.
And there should be `exchange` as well.

**Comment by teambailey** [comment]
Hi @fazamutash - Thank you for reporting this issue! The latest release of 6.0.1 should correct this problem
