### ISSUE TITLE
1 minute websocket connection is inconsistent

### ISSUE THREAD

**Issue by http91** [polygon-io/client-js#88]
Hello,

I don't know whether this is on my end or yours, probably my end. I'm trying to get every stock's 1 minute bar data, started testing with AAPL but even though there are bars, polygon.io sometimes doesn't send them to me, completely skipping them.

For instance, I created a connection at 16:34 today. 

At 16:41, I checked and it turns out it skipped 16:36 and 16:40 bars. My internet connection speed is 50mbps, I can download ~5 megabytes per second.

What could be the problem here?

Here's my code.

```
import { websocketClient } from '@polygon.io/client-js'

const stocksWS = websocketClient('myapikeyishere').stocks()

export async function sleep (ms) {
  return new Promise(resolve => setTimeout(resolve, ms))
}

export async function polygon () {
  await sleep(1000)
  console.log('Started processing data...')
  await stocksWS.send('{"action":"subscribe", "params":"AM.*"}')

  stocksWS.onmessage = async ({ data }) => {
    const [message] = JSON.parse(data)

    if (message.ev === 'AM') {
      const ticker = message.sym

      if (ticker === 'AAPL') {
        console.log(ticker + ' ' + message.s + ' ' + message.ev)
      }
    }
}

polygon()

```

**Comment by teambailey** [comment]
Hi @http91 - Thank you for you're interest in Polygon.io and our JS client!

The code example above appears to be working as expected, with the exception of missing a closing curly brace for the `polygon` function.

So one of the rules that govern what trades can be included in an aggregate query is that if a minute bar doesn't have any eligible trades then the API won't return that minute bar. It's especially common during periods of low trading volume like after market hours, as your reported timestamps indicate, but also for thinly traded tickers during normal market hours as well. That means if the results you are reporting are to be expected if I understand the circumstances correctly.

And apologies for the slow response. 😬 If you have any other issues in the future related unexpected data responses please reach out to our support staff via support@polygon.io or see https://polygon.io/contact for other means of contacting us. Or even better join our public Slack channel. I promise they are super fast in replying and are happy to help with anything!
