### ISSUE TITLE
`IOptionsContractsResult` has incorrect `results` property

### ISSUE THREAD

**Issue by TWilson023** [polygon-io/client-js#95]
`IOptionsContractsResult` has a `results?: IOptionsContractResults[]` property, but according to the [Options Contract docs](https://polygon.io/docs/options/get_v3_reference_options_contracts__options_ticker) this should be an object rather than an array.

It's possible this was mixed up with the [Options Contract**s** endpoint](https://polygon.io/docs/options/get_v3_reference_options_contracts), which does have a `results` array.

**Comment by yehudabortz** [comment]
Hi @TWilson023,
Thank you for reporting this issue! The latest release of 6.0.4 should correct this problem. 🥳
