### ISSUE TITLE
Missing query parameter in multiple reference methods

### ISSUE THREAD

**Issue by TWilson023** [polygon-io/client-js#96]
The reference methods [`dividends`, `stockSplits`, and `stockFinancials`](https://github.com/polygon-io/client-js/blob/master/src/rest/reference/index.ts#L49-L51) in `IReferenceClient` are all missing the corresponding `IDividendsQuery`, `IDividendsQuery `, and `IStockFinancialQuery` query parameters.

**Comment by yehudabortz** [comment]
Hi @TWilson023,
Thank you for reporting this issue! The latest release of 6.0.4 should correct this problem. 🥳
